name: profile

services:
  app:
    image: ghcr.io/norbertx23/profile:${APP_TAG:-latest}
    container_name: profile_app
    restart: unless-stopped
    networks: [edge]
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

networks:
  edge:
    external: true
